# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='modules.proto',
  package='module.chain',
  serialized_pb=_b('\n\rmodules.proto\x12\x0cmodule.chain\"\xac\x01\n\x06Module\x12\x13\n\x0bmodule_name\x18\x01 \x01(\t\x12*\n\ninput_type\x18\x02 \x02(\x0e\x32\x16.module.chain.DataType\x12+\n\x0boutput_type\x18\x03 \x02(\x0e\x32\x16.module.chain.DataType\x12\x15\n\x06is_gpu\x18\x04 \x01(\x08:\x05\x66\x61lse\x12\x1d\n\x15module_implementation\x18\x05 \x03(\t\"Y\n\tChainNode\x12$\n\x06module\x18\x01 \x02(\x0b\x32\x14.module.chain.Module\x12\x0f\n\x07node_id\x18\x02 \x02(\x05\x12\x15\n\rsuccessors_id\x18\x03 \x03(\x05\"/\n\x05\x43hain\x12&\n\x05nodes\x18\x01 \x03(\x0b\x32\x17.module.chain.ChainNode*5\n\x08\x44\x61taType\x12\t\n\x05IMAGE\x10\x00\x12\t\n\x05VIDEO\x10\x01\x12\t\n\x05\x41UDIO\x10\x02\x12\x08\n\x04TEXT\x10\x03')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_DATATYPE = _descriptor.EnumDescriptor(
  name='DataType',
  full_name='module.chain.DataType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='IMAGE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VIDEO', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AUDIO', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TEXT', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=346,
  serialized_end=399,
)
_sym_db.RegisterEnumDescriptor(_DATATYPE)

DataType = enum_type_wrapper.EnumTypeWrapper(_DATATYPE)
IMAGE = 0
VIDEO = 1
AUDIO = 2
TEXT = 3



_MODULE = _descriptor.Descriptor(
  name='Module',
  full_name='module.chain.Module',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='module_name', full_name='module.chain.Module.module_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='input_type', full_name='module.chain.Module.input_type', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='output_type', full_name='module.chain.Module.output_type', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_gpu', full_name='module.chain.Module.is_gpu', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='module_implementation', full_name='module.chain.Module.module_implementation', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=204,
)


_CHAINNODE = _descriptor.Descriptor(
  name='ChainNode',
  full_name='module.chain.ChainNode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='module', full_name='module.chain.ChainNode.module', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='node_id', full_name='module.chain.ChainNode.node_id', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='successors_id', full_name='module.chain.ChainNode.successors_id', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=206,
  serialized_end=295,
)


_CHAIN = _descriptor.Descriptor(
  name='Chain',
  full_name='module.chain.Chain',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nodes', full_name='module.chain.Chain.nodes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=297,
  serialized_end=344,
)

_MODULE.fields_by_name['input_type'].enum_type = _DATATYPE
_MODULE.fields_by_name['output_type'].enum_type = _DATATYPE
_CHAINNODE.fields_by_name['module'].message_type = _MODULE
_CHAIN.fields_by_name['nodes'].message_type = _CHAINNODE
DESCRIPTOR.message_types_by_name['Module'] = _MODULE
DESCRIPTOR.message_types_by_name['ChainNode'] = _CHAINNODE
DESCRIPTOR.message_types_by_name['Chain'] = _CHAIN
DESCRIPTOR.enum_types_by_name['DataType'] = _DATATYPE

Module = _reflection.GeneratedProtocolMessageType('Module', (_message.Message,), dict(
  DESCRIPTOR = _MODULE,
  __module__ = 'modules_pb2'
  # @@protoc_insertion_point(class_scope:module.chain.Module)
  ))
_sym_db.RegisterMessage(Module)

ChainNode = _reflection.GeneratedProtocolMessageType('ChainNode', (_message.Message,), dict(
  DESCRIPTOR = _CHAINNODE,
  __module__ = 'modules_pb2'
  # @@protoc_insertion_point(class_scope:module.chain.ChainNode)
  ))
_sym_db.RegisterMessage(ChainNode)

Chain = _reflection.GeneratedProtocolMessageType('Chain', (_message.Message,), dict(
  DESCRIPTOR = _CHAIN,
  __module__ = 'modules_pb2'
  # @@protoc_insertion_point(class_scope:module.chain.Chain)
  ))
_sym_db.RegisterMessage(Chain)


# @@protoc_insertion_point(module_scope)
