# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='data.proto',
  package='modules.data',
  serialized_pb=_b('\n\ndata.proto\x12\x0cmodules.data\"B\n\tTextProto\x12\x0c\n\x04text\x18\x01 \x02(\t\x12\x0e\n\x06length\x18\x02 \x02(\r\x12\x17\n\x0f\x65ncoding_method\x18\x03 \x01(\t\"@\n\nAudioProto\x12\r\n\x05\x61udio\x18\x01 \x02(\x0c\x12\x0e\n\x06length\x18\x02 \x02(\r\x12\x13\n\x0bsample_rate\x18\x03 \x01(\r\"D\n\nImageProto\x12\r\n\x05image\x18\x01 \x02(\x0c\x12\x0e\n\x06length\x18\x02 \x02(\r\x12\x17\n\x0f\x65ncoding_method\x18\x03 \x01(\r\"J\n\nVideoProto\x12(\n\x06\x66rames\x18\x01 \x03(\x0b\x32\x18.modules.data.ImageProto\x12\x12\n\nframe_rate\x18\x02 \x01(\r')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TEXTPROTO = _descriptor.Descriptor(
  name='TextProto',
  full_name='modules.data.TextProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='modules.data.TextProto.text', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='length', full_name='modules.data.TextProto.length', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='encoding_method', full_name='modules.data.TextProto.encoding_method', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=94,
)


_AUDIOPROTO = _descriptor.Descriptor(
  name='AudioProto',
  full_name='modules.data.AudioProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='audio', full_name='modules.data.AudioProto.audio', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='length', full_name='modules.data.AudioProto.length', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sample_rate', full_name='modules.data.AudioProto.sample_rate', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=160,
)


_IMAGEPROTO = _descriptor.Descriptor(
  name='ImageProto',
  full_name='modules.data.ImageProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='modules.data.ImageProto.image', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='length', full_name='modules.data.ImageProto.length', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='encoding_method', full_name='modules.data.ImageProto.encoding_method', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=162,
  serialized_end=230,
)


_VIDEOPROTO = _descriptor.Descriptor(
  name='VideoProto',
  full_name='modules.data.VideoProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frames', full_name='modules.data.VideoProto.frames', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='frame_rate', full_name='modules.data.VideoProto.frame_rate', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=232,
  serialized_end=306,
)

_VIDEOPROTO.fields_by_name['frames'].message_type = _IMAGEPROTO
DESCRIPTOR.message_types_by_name['TextProto'] = _TEXTPROTO
DESCRIPTOR.message_types_by_name['AudioProto'] = _AUDIOPROTO
DESCRIPTOR.message_types_by_name['ImageProto'] = _IMAGEPROTO
DESCRIPTOR.message_types_by_name['VideoProto'] = _VIDEOPROTO

TextProto = _reflection.GeneratedProtocolMessageType('TextProto', (_message.Message,), dict(
  DESCRIPTOR = _TEXTPROTO,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:modules.data.TextProto)
  ))
_sym_db.RegisterMessage(TextProto)

AudioProto = _reflection.GeneratedProtocolMessageType('AudioProto', (_message.Message,), dict(
  DESCRIPTOR = _AUDIOPROTO,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:modules.data.AudioProto)
  ))
_sym_db.RegisterMessage(AudioProto)

ImageProto = _reflection.GeneratedProtocolMessageType('ImageProto', (_message.Message,), dict(
  DESCRIPTOR = _IMAGEPROTO,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:modules.data.ImageProto)
  ))
_sym_db.RegisterMessage(ImageProto)

VideoProto = _reflection.GeneratedProtocolMessageType('VideoProto', (_message.Message,), dict(
  DESCRIPTOR = _VIDEOPROTO,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:modules.data.VideoProto)
  ))
_sym_db.RegisterMessage(VideoProto)


# @@protoc_insertion_point(module_scope)
